name:                quantum-tic-tac-toe
version:             0.1.0.0
github:              "githubuser/gui-test"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gui-test#readme>

dependencies:
- aeson == 1.4.7.1
- base >= 4.7 && < 5
- bytestring == 0.10.10.1
- file-embed == 0.0.13.0
- lucid == 2.9.12
- mtl == 2.2.2
- raw-strings-qq == 1.1
- text == 1.2.4.0
- webviewhs

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -fmax-pmcheck-iterations=10000000

executables:
  quantum-tic-tac-toe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quantum-tic-tac-toe

tests:
  quantum-tic-tac-toe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quantum-tic-tac-toe
